version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: auto-unsubscribe-{{ .ci }}-{{ checksum "package.json" }}
      - run: npm ci
      - save_cache:
          key: auto-unsubscribe-{{ .ci }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a yarn run test --coverage --ci
      - run: xvfb-run -a yarn run build